"""added urole

Revision ID: 661a2ce18c22
Revises: b5851ba160c9
Create Date: 2018-12-05 15:49:23.186428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661a2ce18c22'
down_revision = 'b5851ba160c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('urole', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'urole')
    # ### end Alembic commands ###
