"""topic table

Revision ID: 6ee6935c3c31
Revises: 705055ad2653
Create Date: 2018-12-17 15:03:33.829362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee6935c3c31'
down_revision = '705055ad2653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_topic_name'), 'topic', ['topic_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_topic_name'), table_name='topic')
    op.drop_table('topic')
    # ### end Alembic commands ###
