"""other tabels

Revision ID: 705055ad2653
Revises: 661a2ce18c22
Create Date: 2018-12-12 19:16:49.167051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705055ad2653'
down_revision = '661a2ce18c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_grade_name'), 'grade', ['grade_name'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=64), nullable=True),
    sa.Column('color_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_color_id'), 'subject', ['color_id'], unique=False)
    op.create_index(op.f('ix_subject_subject_name'), 'subject', ['subject_name'], unique=False)
    op.create_table('revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.String(length=64), nullable=True),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=140), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade'], ['grade.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_start_date'), 'revision', ['start_date'], unique=False)
    op.create_index(op.f('ix_revision_timestamp'), 'revision', ['timestamp'], unique=False)
    op.create_index(op.f('ix_revision_topic'), 'revision', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revision_topic'), table_name='revision')
    op.drop_index(op.f('ix_revision_timestamp'), table_name='revision')
    op.drop_index(op.f('ix_revision_start_date'), table_name='revision')
    op.drop_table('revision')
    op.drop_index(op.f('ix_subject_subject_name'), table_name='subject')
    op.drop_index(op.f('ix_subject_color_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_grade_grade_name'), table_name='grade')
    op.drop_table('grade')
    # ### end Alembic commands ###
