"""Iter and date format

Revision ID: a0e49c6968ee
Revises: 6ee6935c3c31
Create Date: 2019-01-11 10:32:40.243212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e49c6968ee'
down_revision = '6ee6935c3c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iteration', sa.String(length=64), nullable=True),
    sa.Column('date_format', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_date_format'), 'calendar', ['date_format'], unique=False)
    op.create_index(op.f('ix_calendar_iteration'), 'calendar', ['iteration'], unique=False)
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_calendar_iteration'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_date_format'), table_name='calendar')
    op.drop_table('calendar')
    # ### end Alembic commands ###
